services:
  web:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8082:80"
    labels:
      - "dashsync.enable=true"
      - "dashsync.name=Chainle"
      - "dashsync.group=Websites"
      - "dashsync.url=https://chainle.ru"
      - "dashsync.icon=nginx"
      - "dashsync.description=Static site served via nginx"
      - "dashsync.homepage.server=my-docker"
      - "dashsync.homepage.container=chainleru-web-1"
      - "dashsync.homepage.showStats=true"
